### ISSUE TITLE
页面似乎有问题

### ISSUE THREAD

**Issue by FrankchenCjc** [JalorOo/JalorOo.github.io#1]
似乎用的是md在这里写的喵滴的介绍。使用android端firefox68.4.2直接查看的时候会出现问题。
![Screenshot_2020-02-01-00-30-32](https://user-images.githubusercontent.com/45476087/73557078-8faf6180-448b-11ea-9299-24673538aba3.png)
查看页面源码则是出现了转义字符
![Screenshot_2020-02-01-00-30-52](https://user-images.githubusercontent.com/45476087/73557184-b79ec500-448b-11ea-81da-f064e6a80825.png)
我不知道github.io对于md内联的html支持是不是有什么奇怪的属性。（没用过的垃圾人）没法提建议。不过直接全用html可能有效。
这只是个小问题，常用md的应该都知道，不过商业化软件的话，还是少点问题为妙。

**Comment by JalorOo** [comment]
好的，这个问题会尽快调整，感谢反馈！
